### ISSUE TITLE
Is it possible to make it work with XeLatex ?

### ISSUE THREAD

**Issue by fpiou** [loopspace/pgfmorepages#3]
Thanks a lot for this package, it works very well.

I tried it with XeLatex but unfortunately it doesn't work. : there is only one page, no error.

**Comment by loopspace** [comment]
Can you give a little more detail about what you were doing?  With some example code that demonstrates the problem then I can dig around and see what's going on, but without that then it's hard to know where to start.

Thanks!

**Comment by fpiou** [comment]
Yes  ! Here is an example to write 12 identical pages on one page.

https://mega.nz/#F!mNsVALiJ!QRXwFXIONdYWvfoCa7OXZQ

It doesn't work when i compile with XeLatex.

Thanks for your response.

Frédéric

**Comment by loopspace** [comment]
Done a bit of digging around in this and it would appear that the code which set the page sizes wasn't working correctly.  Fortunately, this seems to have been fixed in the original `pgfpages` so I imported the fix into `pgfmorepages` as https://github.com/loopspace/pgfmorepages/commit/e26e5e2e6ad3af35ac01e55af299b3af029c76c9

Could you test and see if that fixes it for you?  It seems to work now on my system.

**Comment by fpiou** [comment]
Hi !
It works fine indeed with the fix on my system.
Thanks !

**Comment by loopspace** [comment]
Great!  I'll try to get that on CTAN soon.
